### ISSUE TITLE
redirect url

### ISSUE THREAD

**Issue by yanb2016** [patw0929/react-native-amplify-user-pool-with-social-idp-example#1]
Hi there， 

Thanks for posting this example. I just started building mobile app using RN, wondering how to set the Redirect URI to return to the app after getting authentication. 
Thank you.

Yanbin

**Comment by yanb2016** [comment]
To make my question clear, I will rewrite my question. When you set const REDIRECT_URI = 'rnampexample://callback/';  why do you use "rnampexample"?  Is that something related to app name or just a random string?

**Comment by patw0929** [comment]
It's scheme url which defined in [`Info.plist`](https://github.com/patw0929/react-native-amplify-user-pool-with-social-idp-example/blob/41f62b542a3babf01af5ad8aad2309c8acab0898/ios/AmplifyUserPoolSocialIdp/Info.plist#L32) (for iOS) and [`AndroidManifest.xml`](https://github.com/patw0929/react-native-amplify-user-pool-with-social-idp-example/blob/41f62b542a3babf01af5ad8aad2309c8acab0898/android/app/src/main/AndroidManifest.xml#L26) (for Android).

**Comment by yanb2016** [comment]
thanks for your reply. After setting the schema, I just copied your code to run on my machine. The callback works but encountered other issues. When getIdToken() method was called, it returns 'network error", it seems an error related to CORS.  And I didn't find the new user added to the user pool. Any suggestion? thanks.
